version: '2'
services:
    mauthp:
        image: rabbitmq:3.8.0-management-alpine
        container_name: "mauthp"
        ports:
            - 15672:15672
            - 1883:1883
        volumes:
            - ./rabbitmq/:/etc/rabbitmq
    mqttadmin:
        image: mqttadmin
        build: ./mqttadmin
        container_name: "mqttadmin"
        ports:
            - 3000:3000
        links:
            - authdb
        depends_on:
            - mauthp
    authdb:
        image: mongo:latest
        container_name: "authdb"
        environment:
          - MONGO_DATA_DIR=/data/db
        volumes:
          - .authdb/data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --profile=2
    logger:
        image: logger
        build: ./logger
        container_name: "logger"
        links:
            - logdb
            - mauthp
        depends_on:
            - logdb
    logdb:
        image: mongo:latest
        container_name: "logdb"
        environment:
          - MONGO_DATA_DIR=/data/db
        volumes:
          - .logdb/data/db:/data/db
        ports:
            - 27018:27017
        command: mongod --profile=2
